### ISSUE TITLE
ModuleNotFoundError: No module named 'yacs

### ISSUE THREAD

**Issue by LnSCV** [MCG-NKU/SOD100K#21]
when run "python test.py --config configs/csnet-L-x2.yml",I met this error. The 'yacs is a packge written by yourself or come with python. Please help me. Thank you and best wish.
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    from configs import cfg
  File "/home/sln/SOD/SOD100K-master/CSNet_training/configs/__init__.py", line 2, in <module>
    from .defaults import _C as cfg
  File "/home/sln/SOD/SOD100K-master/CSNet_training/configs/defaults.py", line 2, in <module>
    from yacs.config import CfgNode as CN
ModuleNotFoundError: No module named 'yacs

**Comment by gasvn** [comment]
you need to install it with pip

**Comment by LnSCV** [comment]
Thank you for your prompt reply .

> you need to install it with pip
